MFI main application code
READIGenz/ads_mfi_main_app pull request #1
Opened 2024-08-12 11:58 UTC by ankitadattatraymore

2024-08-12 13:34 UTC, READIGenz requested changes
overall PR looks good changes needed on the package name

2024-08-12 13:34 UTC, READIGenz commented on src/main/java/mfi/application/demo/MFIApp.java
> +@ComponentScan(basePackages = {"com.example","mfi.application"})
please use better package name

2024-08-12 13:34 UTC, READIGenz commented on src/main/java/mfi/application/demo/UrlConstants.java
> +package mfi.application.demo;
please use a better package name

2024-08-12 13:34 UTC, READIGenz commented on src/test/java/mfi/application/demo/ConsumerUiApplicationTests.java
> +package mfi.application.demo;
pls use a better package name

2024-08-14 07:25 UTC, ankitadattatraymore commented on src/main/java/mfi/application/demo/UrlConstants.java
> +package mfi.application.demo;
should I keep package name as mfi.main.app

2024-08-14 13:27 UTC, READIGenz approved these changes
approved with changes

2024-08-14 13:27 UTC, READIGenz commented on src/main/java/mfi/application/demo/HomeController.java
> +package mfi.application.demo;
pls use a other package name apart from demo

2024-08-14 13:27 UTC, READIGenz commented on src/main/java/mfi/application/demo/UrlConstants.java
> +package mfi.application.demo;
Yes, looks relevant.
or just mfi.app is ok as well.

2024-08-21 06:27 UTC, ankitadattatraymore commented on src/main/java/mfi/application/demo/HomeController.java
> +package mfi.application.demo;
done.

2024-08-21 06:28 UTC, merged