Integrated File to Excel Conversion with Main App
READIGenz/ads_mfi_main_app pull request #3
Opened 2024-09-11 12:30 UTC by SwaroopGenZ

2024-09-12 09:50 UTC, READIGenz requested changes

2024-09-12 09:50 UTC, READIGenz commented on src/main/java/com/mfi/app/UrlConstants.java
> +    public static final String TXT_INPUT = "textInput";
please move these constants into properties file. Especially the Err constants,

2024-09-12 09:50 UTC, READIGenz commented on src/main/java/com/mfi/app/HomeController.java
> +            return ResponseEntity.status(500).body(SERVER_ERR);
pls use constants for Error code 500

2024-09-13 07:28 UTC, SwaroopGenZ commented on src/main/java/com/mfi/app/UrlConstants.java
> +    public static final String TXT_INPUT = "textInput";
Done

2024-09-13 07:28 UTC, SwaroopGenZ commented on src/main/java/com/mfi/app/HomeController.java
> +            return ResponseEntity.status(500).body(SERVER_ERR);
Done

2024-09-13 12:07 UTC, READIGenz approved these changes
approved with suggestions

2024-09-13 12:07 UTC, READIGenz commented on src/main/resources/application.properties
> +FILE_ERR=File is empty
Dear Swaroop, please use a different property file for error codes. please do not use aplication.properties.

2024-09-16 04:53 UTC, merged